apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic:${}@elasticsearch-es-http.default.svc.cluster.local:9200
    esIndexCleaner:
        enabled: true
        numberOfDays: 3
        schedule: "0 0 * * * "
