version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: cd go/house-server; go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: cd go/serverless/auth; go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: cd go; go build ./...
      - run: cd go; go test ./...
