version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: cd services/house-server; go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: cd services/house-server; go build ./...
      - run: cd services/house-server; go test ./...
      - run: cd services/auth; go run github.com/golangci/golangci-lint/cmd/golangci-lint run
      - run: cd services/auth; go build ./...
      - run: cd services/auth; go test ./...
