apiVersion: apps/v1
kind: Deployment
metadata:
  name: house
spec:
  selector:
    matchLabels:
      app: house
  replicas: 1
  template:
    metadata:
      labels:
        app: house
    spec:
      containers:
      - name: house
        image: eu.gcr.io/tensile-imprint-156310/house:08012020_0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
